### ISSUE TITLE
HorizontalHelpWidget misalignments

### ISSUE THREAD

**Issue by solid-danylosafonov** [solid-software/help_ukraine_widget#25]
firefox 104.0.1 (64-bit) @ mbp m1 13
renderer: html

main view: wrong text spacing leads to overflow
![image](https://user-images.githubusercontent.com/112557452/187868206-e786f684-66d0-4029-9602-72d6af4cb4d1.png)

options view: looks about right
![image](https://user-images.githubusercontent.com/112557452/187869636-480e323b-83b8-4ba6-bd7f-6bb5c01414d2.png)

collapsed: perfect
![image](https://user-images.githubusercontent.com/112557452/187870474-9d66eae5-ccee-47f7-aa10-22782ae25775.png)

Safari 15.6.1 @ mbp m1 13
renderer: html

collapsed: perfect
![image](https://user-images.githubusercontent.com/112557452/187875086-7f7dd22e-0b4a-4cdf-b690-30c07210c88c.png)

main: literally everything is mismatched (cross is normally in center but sometimes it is like on screenshot)
![image](https://user-images.githubusercontent.com/112557452/187875781-066a7102-116f-4e71-a85e-80c05358832a.png)

options: wrong spacing between column items, heart icon too small
![image](https://user-images.githubusercontent.com/112557452/187876329-1069f54a-3693-4775-a278-a120885d08f4.png)

**Comment by solid-yuriiprykhodko** [comment]
Chrome Version 104.0.5112.101 (Official Build) (x86_64), 
Renderer: `html`

Container width too small
<img width="360" alt="image" src="https://user-images.githubusercontent.com/40931732/187877687-7a55c55a-9a3e-4b91-bc4c-bc77417a9cb7.png">

Text spacing off
Close button placement a little off
<img width="387" alt="image" src="https://user-images.githubusercontent.com/40931732/187877804-972d1ce4-b76b-4608-98ca-ec99fe184804.png">


Second view -- about the same as comment above
<img width="377" alt="image" src="https://user-images.githubusercontent.com/40931732/187877989-7159fb83-8527-47e1-ad91-f675c06aa0f7.png">

**Comment by solid-yuriiprykhodko** [comment]
Running against MacOS yields similar results as Firefox:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/40931732/187880366-d1b6fd14-9dc1-4b1b-a88a-e7dab8d932d8.png">
